# Generated by Django 2.2 on 2023-02-07 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_code', models.CharField(db_index=True, help_text='折扣代码', max_length=36, unique=True)),
                ('quota', models.FloatField(default=0, help_text='折扣额度')),
                ('note', models.CharField(blank=True, help_text='折扣备注', max_length=128, null=True)),
                ('permissions', models.IntegerField(choices=[(0, '公开'), (1, '私有')], default=0, help_text='权限')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'db_table': 'discount_amount',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='SKU', max_length=36)),
                ('zh_name', models.CharField(db_index=True, help_text='中文名称', max_length=128, unique=True)),
                ('en_name', models.CharField(blank=True, help_text='英文名称', max_length=256, null=True)),
                ('sub_name', models.CharField(blank=True, help_text='副标题', max_length=128, null=True)),
                ('classify', models.IntegerField(choices=[(0, '整箱待发'), (1, '单品选购')], default=0, help_text='下单模式')),
                ('url_path', models.CharField(help_text='URL链接', max_length=48, unique=True)),
                ('goods_index', models.IntegerField(default=0, help_text='排序')),
                ('is_sell_well', models.BooleanField(default=False, help_text='是否是热销')),
                ('gbp_amount', models.DecimalField(decimal_places=0, help_text='英镑零售价', max_digits=10)),
                ('discount_gbp_amount', models.DecimalField(decimal_places=0, help_text='英镑活动价', max_digits=10)),
                ('tax_gbp_amount', models.DecimalField(decimal_places=0, help_text='英镑商品税费', max_digits=10)),
                ('freight_gbp_amount', models.DecimalField(decimal_places=0, help_text='英镑商品运费', max_digits=10)),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新更新日期')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='属性名称', max_length=36)),
                ('alias', models.CharField(help_text='别名', max_length=36)),
                ('attr_index', models.IntegerField(default=0, help_text='排序')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
            ],
            options={
                'db_table': 'goods_attributes',
            },
        ),
        migrations.CreateModel(
            name='GoodsAttributesGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='属性组名称', max_length=36)),
                ('alias', models.CharField(help_text='别名', max_length=36)),
                ('attr_index', models.IntegerField(default=0, help_text='排序')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
            ],
            options={
                'db_table': 'goods_attributes_group',
            },
        ),
        migrations.CreateModel(
            name='GoodsBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(db_index=True, help_text='英文品牌名', max_length=64)),
                ('zh_name', models.CharField(db_index=True, help_text='中文品牌名', max_length=64)),
                ('url_path', models.CharField(help_text='URL名称', max_length=36)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
            ],
            options={
                'db_table': 'goods_brand',
            },
        ),
        migrations.CreateModel(
            name='GoodsClassify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='商品分类名称', max_length=48, unique=True)),
                ('url_path', models.CharField(db_index=True, help_text='URl名称', max_length=36)),
                ('parent_classify', models.CharField(blank=True, help_text='上级分类', max_length=48, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
            ],
            options={
                'db_table': 'goods_classify',
            },
        ),
        migrations.CreateModel(
            name='GoodsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='标签名称', max_length=32, unique=True)),
                ('content', models.CharField(blank=True, help_text='标签描述', max_length=64, null=True)),
                ('index', models.IntegerField(default=0, help_text='标签排序')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
            ],
            options={
                'db_table': 'goods_tag',
            },
        ),
        migrations.CreateModel(
            name='PriceLevelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='价格组代码', max_length=36, unique=True)),
                ('name', models.CharField(db_index=True, help_text='价格组名称', max_length=36, unique=True)),
                ('note', models.CharField(blank=True, help_text='价格组备注', max_length=128, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
            ],
            options={
                'db_table': 'price_level_group',
            },
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_key', models.CharField(blank=True, help_text='md5 key', max_length=64, null=True)),
                ('url_path', models.CharField(blank=True, help_text='图片地址', max_length=128, null=True)),
                ('image', models.TextField(blank=True, help_text='图片base64', null=True)),
            ],
            options={
                'db_table': 'upload_image',
            },
        ),
        migrations.CreateModel(
            name='GoodsBrandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classify', models.IntegerField(choices=[(0, '缩略图'), (1, '品牌横幅')], default=0)),
                ('image', models.TextField(help_text='图片')),
                ('goods_brand', models.ForeignKey(help_text='品牌', on_delete=django.db.models.deletion.CASCADE, to='webapp.GoodsBrand')),
            ],
            options={
                'db_table': 'goods_brand_image',
            },
        ),
        migrations.CreateModel(
            name='GoodsBrandContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, help_text='内容描述', null=True)),
                ('goods_brand', models.ForeignKey(help_text='品牌', on_delete=django.db.models.deletion.CASCADE, to='webapp.GoodsBrand')),
            ],
            options={
                'db_table': 'goods_brand_context',
            },
        ),
        migrations.CreateModel(
            name='GoodsBindTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
                ('goods', models.ForeignKey(blank=True, help_text='商品', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Goods')),
                ('tag', models.ForeignKey(blank=True, help_text='商品标签', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.GoodsTag')),
            ],
            options={
                'db_table': 'goods_bind_tag',
            },
        ),
        migrations.CreateModel(
            name='GoodsBindAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
                ('goods', models.ForeignKey(blank=True, help_text='商品', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.Goods')),
                ('goods_attr', models.ManyToManyField(blank=True, help_text='商品属性', to='webapp.GoodsAttributes')),
            ],
            options={
                'db_table': 'goods_bind_attr',
            },
        ),
        migrations.AddField(
            model_name='goodsattributes',
            name='attr_group',
            field=models.ForeignKey(help_text='属性组', on_delete=django.db.models.deletion.CASCADE, to='webapp.GoodsAttributesGroup'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_brand',
            field=models.ForeignKey(blank=True, help_text='品牌', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.GoodsBrand'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_classify',
            field=models.ForeignKey(blank=True, help_text='分类', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.GoodsClassify'),
        ),
        migrations.CreateModel(
            name='DiscountLevelGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='最新一次更新')),
                ('goods', models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='webapp.Goods')),
                ('price_level_group', models.ForeignKey(help_text='商品价格分组', on_delete=django.db.models.deletion.CASCADE, to='webapp.PriceLevelGroup')),
            ],
            options={
                'db_table': 'discount_level_goods',
            },
        ),
        migrations.CreateModel(
            name='DiscountAmountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bind_date', models.DateTimeField(auto_now_add=True, help_text='绑定日期')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='最后更新日期')),
                ('binding_person', models.ForeignKey(blank=True, help_text='绑定人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='binding_person', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, help_text='折扣', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.DiscountAmount')),
                ('user', models.ForeignKey(blank=True, help_text='用户', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discount_amount_user',
            },
        ),
        migrations.AddField(
            model_name='discountamount',
            name='level_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.PriceLevelGroup'),
        ),
        migrations.AddField(
            model_name='discountamount',
            name='updater',
            field=models.ForeignKey(blank=True, help_text='更新人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
