# Generated by Django 2.2 on 2023-02-07 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.CharField(db_index=True, help_text='会员号', max_length=24)),
                ('phone', models.CharField(blank=True, help_text='联系方式', max_length=24, null=True)),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女'), (3, '保密')], default=0, help_text='性别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_member',
            },
        ),
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, help_text='昵称', max_length=48)),
                ('profile_photo', models.CharField(blank=True, help_text='头像', max_length=128, null=True)),
                ('manage_number', models.CharField(db_index=True, help_text='编号', max_length=24)),
                ('phone', models.CharField(blank=True, help_text='联系方式', max_length=24, null=True)),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女'), (3, '保密')], default=0, help_text='性别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_user',
            },
        ),
    ]
